Repository openHPI/monitoring-frontend, pull requests merged in 2019-03, with the labels that each got.

#21 Feature/advanced snooze options
  src/apis/BackendApi.ts
  src/components/AlertLine.vue
  src/components/SnoozeModal.vue
  src/interfaces/Alert.ts
  src/interfaces/KapacitorEvent.ts
  src/views/AlertList.vue
Labels: enhancement, frontend

#11 Add mnemosyne integration, implement basic snooze function and add config
  .gitignore
  src/apis/BackendApi.ts
  src/components/AlertLine.vue
Labels: enhancement, frontend

#19 Feature/edit and delete tasks
  src/apis/KapacitorApi.ts
  src/components/TaskVariablesModal.vue
  src/interfaces/KapacitorTask.ts
  src/interfaces/KapacitorTaskVariable.ts
  src/interfaces/KapacitorTaskVariables.ts
Labels: enhancement, frontend, kapacitor

#16 Feature/grafana iframe integration
  src/components/AlertLine.vue
  src/interfaces/Alert.ts
  src/interfaces/KapacitorEvent.ts
  src/views/AlertList.vue
Labels: enhancement, frontend

#22 Event Searchbar
  package.json
  src/views/AlertList.vue
Labels: enhancement, frontend

#24 Styled detail text
  src/components/AlertLine.vue
Labels: enhancement, frontend

#25 Fix/alert level
  src/apis/BackendApi.ts
  src/apis/KapacitorApi.ts
  src/views/Dashboard.vue
Labels: bug, frontend, kapacitor
